name: Daily check in

on:
  schedule:
    - cron: "0 22 * * *"  # scheduled at 06:00 (UTC+8) everyday
  workflow_dispatch:

jobs:
  check-in:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # Restore counter.json from cache
      - name: Restore counter cache
        uses: actions/cache@v3
        id: counter-cache
        with:
          path: counter.json
          key: counter-${{ github.ref }}
          restore-keys: |
            counter-${{ github.ref }}

      # Initialize counter.json if it doesn't exist
      - name: Initialize counter.json
        run: |
          if [ ! -f counter.json ]; then
            echo '{"processCounter":0}' > counter.json
          fi
          echo "Current counter value: $(cat counter.json)"

      - name: Check In
        run: node index.js
        env:
          COOKIE: ${{ secrets.COOKIE }}
          GAMES: ${{ vars.GAMES }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USER: ${{ secrets.DISCORD_USER }}

      # Save counter.json to cache
      - name: Save counter cache
        uses: actions/cache@v3
        if: always()  # Save even if previous steps fail
        with:
          path: counter.json
          key: counter-${{ github.ref }}
          restore-keys: |
            counter-${{ github.ref }}

  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
