name: Daily check in

on:
  schedule:
    - cron: "0 22 * * *"  # scheduled at 06:00 (UTC+8) everyday
  workflow_dispatch:

jobs:
  check-in:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # Download counter.json artifact from previous run if it exists
      - name: Download previous counter.json
        uses: actions/download-artifact@v4
        with:
          name: process-counter
          path: .
          if-no-files-found: ignore

      # Initialize counter.json if it doesn't exist
      - name: Initialize counter.json (if not exists)
        run: |
          if [ ! -f counter.json ]; then
            echo '{"processCounter":0}' > counter.json
          fi

      - name: Check In
        run: node index.js
        env:
          COOKIE: ${{ secrets.COOKIE }}
          GAMES: ${{ vars.GAMES }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USER: ${{ secrets.DISCORD_USER }}

      # Upload the updated counter.json for next run
      - name: Upload updated counter.json
        uses: actions/upload-artifact@v4
        with:
          name: process-counter
          path: counter.json
          retention-days: 2  # Keep for 1 day to ensure it's available for next run

  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
