name: Daily check in

on:
  schedule:
    - cron: "0 22 * * *"
  workflow_dispatch:

jobs:
  check-in:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Download counter artifact
        id: download-artifact
        run: |
          mkdir -p counter
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: counter-artifact
          path: counter

      - name: Restore or Initialize counter.json
        run: |
          if [ -f counter/counter.json ]; then
            cp counter/counter.json counter.json
          else
            echo '{"processCounter":0}' > counter.json
          fi
          cat counter.json

      - name: Run Check-In Script
        run: node index.js
        env:
          COOKIE: ${{ secrets.COOKIE }}
          GAMES: ${{ vars.GAMES }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USER: ${{ secrets.DISCORD_USER }}

      - name: Upload counter.json as artifact
        uses: actions/upload-artifact@v4
        with:
          name: counter-artifact
          path: counter.json
          overwrite: true  # v4 supports artifact overwrites!

  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
