name: Daily check in

on:
  schedule:
    - cron: "0 22 * * *"
  workflow_dispatch:

jobs:
  check-in:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Ensure counter directory exists
        run: mkdir -p counter

      - name: Try to download previous counter artifact (optional)
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: counter-artifact
          path: counter

      - name: Restore or Initialize counter.json
        run: |
          if [ -f counter/counter.json ]; then
            echo "Found existing counter. Restoring."
            cp counter/counter.json counter.json
          else
            echo "No counter found. Initializing new one."
            echo '{"processCounter":0}' > counter.json
          fi
          cat counter.json

      - name: Run Check-In Script
        run: node index.js
        env:
          COOKIE: ${{ secrets.COOKIE }}
          GAMES: ${{ vars.GAMES }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USER: ${{ secrets.DISCORD_USER }}

      - name: Move counter.json into folder for upload
        run: |
          mkdir -p counter
          cp counter.json counter/counter.json

      - name: Upload updated counter.json
        uses: actions/upload-artifact@v4
        with:
          name: counter-artifact
          path: counter
          overwrite: true

  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
