name: Daily check in

on:
  schedule:
    - cron: "0 22 * * *"
  workflow_dispatch:

jobs:
  check-in:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Ensure counter directory exists
        run: mkdir -p counter

      - name: Restore counter from cache
        id: restore-counter
        uses: actions/cache@v4
        with:
          path: counter/counter.json
          key: counter-key-${{ github.run_number }}
          restore-keys: |
            counter-key

      - name: Restore or Initialize counter.json
        run: |
          if [ -f counter/counter.json ]; then
            echo "Found existing counter. Restoring."
            cp counter/counter.json counter.json
          else
            echo "No counter found. Initializing new one."
            echo '{"processCounter":0}' > counter.json
          fi
          cat counter.json

      - name: Run Check-In Script
        run: node index.js
        env:
          COOKIE: ${{ secrets.COOKIE }}
          GAMES: ${{ vars.GAMES }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USER: ${{ secrets.DISCORD_USER }}

      - name: Move counter.json into folder for cache update
        run: |
          mkdir -p counter
          cp counter.json counter/counter.json

      - name: Save updated counter to cache
        uses: actions/cache@v4
        with:
          path: counter/counter.json
          key: counter-key-${{ github.run_number }}
          restore-keys: |
            counter-key

  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
