name: Daily check in
on:
  schedule:
    - cron: "0 22 * * *"
  workflow_dispatch:
jobs:
  check-in:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Need write permission to push changes back to repo
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      
      # Initialize counter.json if it doesn't exist
      - name: Initialize counter if needed
        run: |
          mkdir -p counter
          if [ ! -f counter/counter.json ]; then
            echo "No counter found. Initializing new one."
            echo '{"processCounter":0,"lastUpdated":"2025-04-30T00:00:00.000Z"}' > counter/counter.json
          fi
          echo "Current counter state:"
          cat counter/counter.json
      
      # Run the check-in script
      - name: Run Check-In Script
        run: node index.js
        env:
          COOKIE: ${{ secrets.COOKIE }}
          GAMES: ${{ vars.GAMES }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USER: ${{ secrets.DISCORD_USER }}
      
      # Debug output to verify counter is updated
      - name: Show updated counter
        run: |
          echo "Updated counter state:"
          cat counter/counter.json
      
      # Commit and push the updated counter back to the repository
      - name: Commit and push counter updates
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add counter/counter.json
          git commit -m "Update counter after check-in [skip ci]" || echo "No changes to commit"
          git push
  
  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
